[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[dev]
  command = "npm run dev"
  targetPort = 5173
  port = 8888
  publish = "dist"
  autoLaunch = true

# Enable WLO proxy function only when WLO_PROXY_ENABLED is true
[functions]
  included_files = ["netlify/functions/wlo-proxy.ts"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200